export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const GET_COMPANY_REQUEST = "GET_COMPANY_REQUEST";
export const GET_COMPANY_SUCCESS = "GET_COMPANY_SUCCESS";
export const GET_COMPANY_FAIL = "GET_COMPANY_FAIL";

export const GET_COMPANY_BYID_FAIL = "GET_COMPANY_BYID_FAIL";
export const GET_COMPANY_BYID_REQUEST = "GET_COMPANY_BYID_REQUEST";
export const GET_COMPANY_BYID_SUCCESS = "GET_COMPANY_BYID_SUCCESS";
