export const MEMBER_DETAILS_REQUEST = "MEMBER_DETAILS_REQUEST";
export const MEMBER_DETAILS_SUCCESS = "MEMBER_DETAILS_SUCCESS";
export const MEMBER_DETAILS_FAIL = "MEMBER_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
