version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/project
hooks:
  BeforeInstall:
      - location: scripts/beforeInstall.bash
  AfterInstall:
      - location: scripts/afterInstall.bash
