version: 0.2
 phases:
   pre_build:
     commands:
       - echo Installing source NPM dependencies...
       - npm ci --legacy-peer-deps
   build:
     commands:
       - echo Build started on `date`
       - echo Compiling the dist folder
       - export NODE_OPTIONS="--max-old-space-size=3072"
       - npm run build
