import React, { useEffect, useRef, useState } from "react";
import {
  Paper,
  Box,
  Typography,
  Grid,
  TableContainer,
  Table,
  TableHead,
  TableCell,
  TableBody,
  TableRow,
  Button,
} from "@mui/material";
import LeftArrowIcon from "../../assets/Images/CommonImages/GoLeft.png";
import PrintPurchaseOrder from "../../assets/Images/CommonImages/Print.png";

import axios from "axios";

import BreadCrumbHeader from "../../components/Header/BreadCrumbHeader";
import { useNavigate, useParams } from "react-router-dom";
import { useGetOrderSummaryByIdForBuyer } from "../../Hooks/OrderActions/useGetOrderSummaryByIdForBuyer";
import { getCompanyById } from "../../redux/action/CompanyActions";
import { useDispatch, useSelector } from "react-redux";
import DocDownloadImg from "../../assets/Images/CommonImages/DocDownload.png";
import { getOrderSummary } from "../../redux/action/OrderSummaryActions";
import { ToastContainer, toast } from "react-toastify";
import { useGetInvoiceByOrderSummary } from "../../Hooks/Invoices/useGetInvoiceByOrderSummary";
import { useReactToPrint } from "react-to-print";
import NumberToWord from "../../components/NumberToWord";
import { notifications } from "../../redux/action/Notification/notification";

const FinalInvoice = () => {
  const downloadRef = useRef(null);
  const componentRef = useRef();
  const handlePrint = useReactToPrint({
    content: () => componentRef.current,
  });
  const handlePrint1 = useReactToPrint({
    content: () => componentRef.current,
  });
  let dispatch = useDispatch();
  const [mutateResponse, setMutateResponse] = useState();
  const [notificationOn, setNotificationOn] = useState("");

  const navigate = useNavigate();

  const { id } = useParams();

  const {
    data: InvoiceData,
    isLoading: DataLoading,
    error: DataError,
  } = useGetInvoiceByOrderSummary(id);

  const printRef = useRef();
  const handlePrintClick = () => {
    window.print(printRef.current.innerHTML);
  };

  let IsMedia;
  InvoiceData?.ProductData?.map((res) => {
    if (res?.ProductTypeName === "Media") {
      IsMedia = true;
    }
  });

  const { data: orderSummaryData, isLoading: orderSummaryLoading } =
    useGetOrderSummaryByIdForBuyer(id);

  let orderData = [];

  for (let i = 0; i < orderSummaryData?.ProductData?.length; i++) {
    orderData.push(orderSummaryData.ProductData[i]);
  }

  let totalPrice = 0;
  orderData?.map((item) => {
    totalPrice += item.DiscountedPrice
      ? item.DiscountedPrice
      : item.PricePerUnit * item.ProductQuantity * item.ProductQuantity;
  });

  const { OrderSummary: OrderSummarydata, loading: OrderSummaryDataLoading } =
    useSelector((state) => state.OrderSummaryD);

  useEffect(() => {
    dispatch(getCompanyById(OrderSummarydata?.SellerCompanyId));
    dispatch(getOrderSummary(id));
  }, [dispatch, id]);

  let storeDataIds = [];
  let TotalQuantity = 0;
  let totalAmount = 0;
  let totalPricePerUnit = 0;
  let totatlTaxableAmount = 0;
  let totalGST = 0;
  let totalAmountWithGST = 0;
  let totalAmountWithTax = 0;
  let TotalAmountAfterTax = 0;
  let TotalDiscount = 0;
  OrderSummarydata?.ProductData?.map((item) => {
    storeDataIds.push(item);
    TotalQuantity += item.ProductQuantity;
    totalAmount += item.DiscountedPrice * item.ProductQuantity;
    totalPricePerUnit += item.DiscountedPrice * item.ProductQuantity;
    totatlTaxableAmount += item.DiscountedPrice * item.ProductQuantity;
    totalGST += item.GST;
    totalAmountWithGST +=
      item?.DiscountedPrice * item?.ProductQuantity * (item?.GST / 100);
    totalAmountWithTax += item?.DiscountedPrice * item?.ProductQuantity;
    TotalDiscount += item?.DiscountedPrice - item?.PricePerUnit;
  });

  let TotalAmountWithTransportationData = Number(totalAmountWithTax);

  TotalAmountAfterTax =
    Number(TotalAmountWithTransportationData) + Number(totalAmountWithTax);

  useEffect(() => {
    if (mutateResponse === "Accepted") {
      alert("Order Accepted");
      navigate("/home/sellerordersummary");
    } else if (mutateResponse === "Rejected") {
      alert("Order Rejected");
      navigate("/home/sellerordersummary");
    } else if (mutateResponse === "Already Accepted") {
      alert("Error");
      navigate("/home/sellerordersummary");
    }
  }, [mutateResponse]);

  useEffect(() => {
    dispatch(
      getCompanyById(orderSummaryData?.OrderSummarydata?.BuyerCompanyId)
    );
  }, [orderSummaryData?.OrderSummarydata?.BuyerCompanyId]);

  useEffect(() => {
    if (notificationOn != "") {
      const sellerId = InvoiceData?.SellerDetails?.SellerCompanyId;
      const buyerId = InvoiceData?.BuyerDetails?.BuyerCompanyId;
      const type = "Order";

      let message = "";
      if (notificationOn === "Accepted") {
        message = `Congratulations, PI generated by you has been confirmed by ${InvoiceData?.BuyerDetails?.BuyerCompanyName}`;
      } else if (notificationOn === "Rejected") {
        message = `Sorry, PI generated by you has got rejected by ${InvoiceData?.SellerDetails?.SellerCompanyName}`;
      }

      dispatch(notifications(sellerId, buyerId, message, type));
    }
  }, [notificationOn]);
  console.log("OrderSummarydata", InvoiceData);
  return (
    <Paper
      sx={{
        bgcolor: "transparent",
        boxShadow: "none",
        width: "100%",
      }}
      elevation={0}
    >
      <ToastContainer
        position="top-center"
        autoClose={5000}
        hideProgressBar
        newestOnTop={false}
        closeOnClick
        rtl={false}
        pauseOnFocusLoss
        draggable
        pauseOnHover
        theme="light"
      />
      <BreadCrumbHeader MainText="Final Invoice" />

      <Paper
        sx={{
          width: "100%",
          bgcolor: "white",
          mx: "auto",
        }}
        elevation={1}
      >
        <Paper
          sx={{
            width: "95%",
            mx: "auto",
            height: "50px",
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            alignContent: "center",
          }}
          elevation={0}
        >
          <Box
            component="img"
            src={LeftArrowIcon}
            sx={{ width: "25px", cursor: "pointer" }}
            onClick={() => navigate("/home/purchaseorderlist")}
          />
          <Box
            sx={{
              display: "flex",
              width: "60px",
              justifyContent: "space-between",
            }}
          >
            <Box
              component="img"
              src={PrintPurchaseOrder}
              sx={{ width: "22px", height: "auto", cursor: "pointer" }}
              onClick={handlePrint}
            />
            <Box
              component="img"
              src={DocDownloadImg}
              sx={{ width: "21px", height: "auto", cursor: "pointer" }}
              onClick={handlePrint}
            />
          </Box>
        </Paper>
        <Box ref={componentRef}>
          <Box
            sx={{
              display: "flex",
              flexDirection: "row",
              justifyContent: "space-between",
              alignItems: "center",
              width: "95%",
              height: "auto",
              mx: "auto",
              borderRight: "1px solid #cdcdcd",
              borderLeft: "1px solid #cdcdcd",
            }}
          >
            <Box
              sx={{
                display: "flex",
                flexDirection: "row",
                justifyContent: "center",
                alignItems: "center",
                borderRight: "1px solid #F3F2F3",
                height: "130px",
                width: "30%",
              }}
            >
              Seller Logo
            </Box>
            <Box
              sx={{
                display: "flex",
                flexDirection: "column",
                justifyContent: "center",
                alignItems: "center",
                borderRight: "1px solid #cdcdcd",
                borderLeft: "1px solid #cdcdcd",
                height: "130px",
                width: "40%",
              }}
            >
              <Typography sx={CommongTextStyle}>
                {OrderSummarydata?.SellerDetails?.SellerCompanyName}
              </Typography>
              <Typography
                sx={{
                  ...CommongTextStyle,
                  textAlign: "center",
                  fontSize: "11px",
                }}
              >
                {OrderSummarydata?.SellerDetails?.SellerCompanyAddress}
              </Typography>
              <Typography>
                Tel:{OrderSummarydata?.SellerDetails?.SellerCompanyContact}
              </Typography>
              <Typography>
                GSTIN:{OrderSummarydata?.SellerDetails?.GSTIN}
              </Typography>
            </Box>
            <Box
              sx={{
                display: "flex",
                flexDirection: "column",
                justifyContent: "center",
                alignItems: "center",
                borderRight: "1px solid #cdcdcd",
                borderLeft: "1px solid #cdcdcd",
                height: "130px",
                width: "30%",
              }}
            >
              <Typography>Seller's website</Typography>
            </Box>
          </Box>
          <Box
            sx={{
              width: "95%",
              height: "42px",
              mx: "auto",
              background: "#156DB6",
              borderRadius: "10px",
              borderRight: "1px solid #cdcdcd",
              borderLeft: "1px solid #cdcdcd",
            }}
          >
            <Typography
              sx={{
                ...CommongTextStyle,
                color: "white",
                display: "flex",
                justifyContent: "center",
                alignItems: "center",
                alignContent: "center",
                height: "100%",
              }}
            >
              Final Invoice
            </Typography>
          </Box>
          <Box
            sx={{
              display: "flex",
              flexDirection: "row",
              justifyContent: "space-between",
              alignItems: "center",
              width: "95%",
              mx: "auto",
              borderRight: "1px solid #cdcdcd",
              borderLeft: "1px solid #cdcdcd",
            }}
          >
            <TableContainer>
              <Table>
                <TableBody>
                  <TableRow>
                    <TableCell sx={{ p: 0.5 }}>
                      <Typography sx={CommongTextStyle}>
                        Invoice Date :{" "}
                        {new Date(OrderSummarydata?.PoDate).toDateString()}
                      </Typography>
                    </TableCell>
                    <TableCell sx={{ p: 0.5 }}>
                      <Typography sx={CommongTextStyle}>
                        Place of Supply:{" "}
                        {OrderSummarydata?.BuyerDetails?.Address?.Discrict}
                      </Typography>
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell sx={{ p: 0.5 }}>
                      <Typography sx={CommongTextStyle}>
                        State :{" "}
                        {OrderSummarydata?.SellerDetails?.Address?.State}
                      </Typography>
                    </TableCell>
                    <TableCell sx={{ p: 0.5 }}>
                      <Typography sx={CommongTextStyle}>
                        Purchase Order no: {InvoiceData?.PINumber}
                      </Typography>
                    </TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </TableContainer>
          </Box>
          <Box
            sx={{
              width: "95%",
              mx: "auto",
              border: "1px solid #cdcdcd",
            }}
          >
            <Box
              sx={{
                width: "100%",
                height: "21px",
                background: "#156DB6",
                borderRadius: "3px 0px 0px 3",
                width: "100%",
                display: "flex",
                justifyContent: "space-between",
                alignItems: "center",
                alignContent: "center",
              }}
            >
              <Box
                sx={{
                  width: "50%",
                  display: "flex",
                  justifyContent: "center",
                  alignItems: "center",
                  alignContent: "center",
                  height: "100%",
                  borderRight: "1px solid #F3F2F3",
                }}
              >
                <Typography
                  sx={{
                    ...CommongTextStyle,
                    fontSize: "10px",
                    color: "white",
                  }}
                >
                  Bill to Party
                </Typography>
              </Box>
              <Box
                sx={{
                  width: "50%",
                  display: "flex",
                  justifyContent: "center",
                  alignItems: "center",
                  alignContent: "center",
                  height: "100%",
                }}
              >
                <Typography
                  sx={{
                    ...CommongTextStyle,
                    color: "white",
                    fontSize: "10px",
                  }}
                >
                  Ship to Party
                </Typography>
              </Box>
            </Box>
            <Box
              sx={{
                display: "flex",
                flexDirection: "row",
                justifyContent: "space-between",
                alignItems: "center",
                width: "100%",
                py: 0,
              }}
            >
              <Box
                sx={{
                  width: "100%",
                  mx: "auto",
                  borderRight: "1px solid #CDCDCD",
                  p: 2,
                }}
              >
                <Table sx={{ p: 0 }}>
                  <TableBody sx={{ p: 0 }}>
                    <TableRow sx={{ p: 0 }}>
                      <TableCell
                        sx={{
                          p: 0.5,
                          borderBottom: "none",
                          width: "90px",
                        }}
                      >
                        <Typography sx={TextStyleTitle}>
                          {" "}
                          Seller name
                        </Typography>
                      </TableCell>
                      <TableCell
                        sx={{
                          p: 0.5,
                          borderBottom: "none",
                        }}
                      >
                        <Typography sx={TextStyleTwo}>
                          {OrderSummarydata?.SellerDetails?.SellerCompanyName}
                        </Typography>
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell
                        sx={{
                          p: 0.5,
                          borderBottom: "none",
                        }}
                      >
                        <Typography sx={TextStyleTitle}> Address </Typography>
                      </TableCell>
                      <TableCell
                        sx={{
                          p: 0.5,
                          borderBottom: "none",
                        }}
                      >
                        <Typography sx={TextStyleTwo}>
                          {
                            OrderSummarydata?.SellerDetails?.Address
                              ?.AddressLine
                          }
                        </Typography>
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell
                        sx={{
                          p: 0.5,
                          borderBottom: "none",
                        }}
                      >
                        <Typography sx={TextStyleTitle}> GSTIN </Typography>
                      </TableCell>
                      <TableCell
                        sx={{
                          p: 0.5,
                          borderBottom: "none",
                        }}
                      >
                        <Typography sx={TextStyleTwo}>
                          {OrderSummarydata?.SellerDetails?.GSTIN}
                        </Typography>
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell
                        sx={{
                          p: 0.5,
                          borderBottom: "none",
                        }}
                      >
                        <Typography sx={TextStyleTitle}> State</Typography>{" "}
                      </TableCell>
                      <TableCell
                        sx={{
                          p: 0.5,
                          borderBottom: "none",
                        }}
                      >
                        <Typography sx={TextStyleTwo}>
                          {OrderSummarydata?.SellerDetails?.Address?.State}
                        </Typography>
                      </TableCell>
                    </TableRow>
                  </TableBody>
                </Table>
              </Box>
              <Box sx={{ width: "100%", mx: "auto", p: 2 }}>
                <Table>
                  <TableBody>
                    <TableRow>
                      <TableCell
                        sx={{
                          p: 0.5,
                          borderBottom: "none",
                          width: "90px",
                        }}
                      >
                        <Typography sx={TextStyleTitle}> Buyer name</Typography>
                      </TableCell>
                      <TableCell
                        sx={{
                          p: 0.5,
                          borderBottom: "none",
                        }}
                      >
                        <Typography sx={TextStyleTwo}>
                          {" "}
                          {OrderSummarydata?.BuyerDetails?.BuyerCompanyName}
                        </Typography>
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell
                        sx={{
                          p: 0.5,
                          borderBottom: "none",
                        }}
                      >
                        <Typography sx={TextStyleTitle}> Address </Typography>
                      </TableCell>
                      <TableCell
                        sx={{
                          p: 0.5,
                          borderBottom: "none",
                        }}
                      >
                        <Typography sx={TextStyleTwo}>
                          {OrderSummarydata?.BuyerDetails?.Address?.AddressLine}
                        </Typography>
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell
                        sx={{
                          p: 0.5,
                          borderBottom: "none",
                        }}
                      >
                        <Typography sx={TextStyleTitle}> GSTIN </Typography>
                      </TableCell>
                      <TableCell
                        sx={{
                          p: 0.5,
                          borderBottom: "none",
                        }}
                      >
                        <Typography sx={TextStyleTwo}>
                          {OrderSummarydata?.BuyerDetails?.GSTIN}
                        </Typography>
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell
                        sx={{
                          p: 0.5,
                          borderBottom: "none",
                        }}
                      >
                        <Typography sx={TextStyleTitle}> State</Typography>{" "}
                      </TableCell>
                      <TableCell
                        sx={{
                          p: 0.5,
                          borderBottom: "none",
                        }}
                      >
                        <Typography sx={TextStyleTwo}>
                          {" "}
                          {OrderSummarydata?.BuyerDetails?.Address?.State}
                        </Typography>{" "}
                      </TableCell>
                    </TableRow>
                  </TableBody>
                </Table>
              </Box>
            </Box>
          </Box>

          <TableContainer
            component={Paper}
            sx={{
              maxWidth: "95%",
              mx: "auto",
            }}
          >
            <Table sx={{ minWidth: "700px" }} aria-label="customized table">
              <TableHead>
                <TableRow sx={{ height: "42px", bgcolor: "#156DB6" }}>
                  <TableCell
                    align="center"
                    colSpan={1}
                    rowSpan={1}
                    sx={{ borderRight: "1px solid #CDCDCD" }}
                  >
                    <Typography sx={TableTextStyle}> S. No.</Typography>
                  </TableCell>
                  <TableCell
                    align="center"
                    colSpan={1}
                    rowSpan={2}
                    sx={{ borderRight: "1px solid #CDCDCD" }}
                  >
                    <Typography sx={TableTextStyle}>
                      Product / Service Description
                    </Typography>
                  </TableCell>
                  <TableCell
                    align="center"
                    colSpan={1}
                    rowSpan={1}
                    sx={{ borderRight: "1px solid #CDCDCD" }}
                  >
                    <Typography sx={TableTextStyle}>HSN Code</Typography>
                  </TableCell>
                  <TableCell
                    align="center"
                    colSpan={1}
                    rowSpan={1}
                    sx={{ borderRight: "1px solid #CDCDCD" }}
                  >
                    <Typography sx={TableTextStyle}>UOM</Typography>
                  </TableCell>
                  <TableCell
                    align="center"
                    colSpan={1}
                    rowSpan={1}
                    sx={{ borderRight: "1px solid #CDCDCD" }}
                  >
                    <Typography sx={TableTextStyle}>QTY</Typography>
                  </TableCell>
                  <TableCell
                    align="center"
                    colSpan={1}
                    rowSpan={1}
                    sx={{ borderRight: "1px solid #CDCDCD" }}
                  >
                    <Typography sx={TableTextStyle}>Rate</Typography>
                  </TableCell>
                  <TableCell
                    align="center"
                    colSpan={1}
                    rowSpan={1}
                    sx={{ borderRight: "1px solid #CDCDCD" }}
                  >
                    <Typography sx={TableTextStyle}>Amount</Typography>
                  </TableCell>
                  <TableCell
                    align="center"
                    colSpan={1}
                    rowSpan={1}
                    sx={{ borderRight: "1px solid #CDCDCD" }}
                  >
                    <Typography sx={TableTextStyle}>Discount</Typography>
                  </TableCell>

                  <TableCell
                    align="center"
                    sx={{
                      bgcolor: "#156DB6",
                      width: "170px",
                      borderLeft: "1px solid #CDCDCD",
                    }}
                  >
                    <Typography sx={TableTextStyle}>Taxable Value</Typography>
                  </TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {OrderSummarydata?.ProductData?.map((row) => {
                  return (
                    <TableRow
                      sx={{
                        height: "42px",
                        backgroundColor: "#F7F7F7",
                      }}
                    >
                      <TableCell
                        align="center"
                        colSpan={1}
                        rowSpan={1}
                        sx={{ borderRight: "1px solid #CDCDCD" }}
                      >
                        <Typography sx={TableBottomtext}>1</Typography>
                      </TableCell>
                      <TableCell
                        align="center"
                        colSpan={1}
                        rowSpan={1}
                        sx={{ borderRight: "1px solid #CDCDCD" }}
                      >
                        <Typography sx={TableBottomtext}>
                          {row?.ProductName}
                        </Typography>
                      </TableCell>
                      <TableCell
                        align="center"
                        colSpan={1}
                        rowSpan={1}
                        sx={{ borderRight: "1px solid #CDCDCD" }}
                      >
                        <Typography sx={TableBottomtext}>9983</Typography>
                      </TableCell>
                      <TableCell
                        align="center"
                        colSpan={1}
                        rowSpan={1}
                        sx={{ borderRight: "1px solid #CDCDCD" }}
                      >
                        <Typography sx={TableBottomtext}>
                          {row?.ProductQuantity}
                        </Typography>
                      </TableCell>
                      <TableCell
                        align="center"
                        colSpan={1}
                        rowSpan={1}
                        sx={{ borderRight: "1px solid #CDCDCD" }}
                      >
                        <Typography sx={TableBottomtext}>
                          {row?.ProductQuantity}
                        </Typography>
                      </TableCell>
                      <TableCell
                        align="center"
                        colSpan={1}
                        rowSpan={1}
                        sx={{ borderRight: "1px solid #CDCDCD" }}
                      >
                        <Typography sx={TableBottomtext}>
                          {row?.DiscountedPrice
                            ? row?.DiscountedPrice
                            : row?.PricePerUnit}
                        </Typography>
                      </TableCell>
                      <TableCell
                        align="center"
                        colSpan={1}
                        rowSpan={1}
                        sx={{ borderRight: "1px solid #CDCDCD" }}
                      >
                        <Typography sx={TableBottomtext}>
                          {row?.DiscountedPrice
                            ? row?.DiscountedPrice
                            : row?.PricePerUnit * row?.ProductQuantity}
                        </Typography>
                      </TableCell>
                      <TableCell
                        align="center"
                        colSpan={1}
                        rowSpan={1}
                        sx={{ borderRight: "1px solid #CDCDCD" }}
                      >
                        <Typography sx={TableBottomtext}>
                          {" "}
                          {row?.DiscountedPrice
                            ? row?.DiscountedPrice - row?.PricePerUnit
                            : row?.DiscountedPrice}
                        </Typography>
                      </TableCell>
                      <TableCell
                        align="center"
                        colSpan={1}
                        rowSpan={1}
                        sx={{ borderRight: "1px solid #CDCDCD" }}
                      >
                        <Typography sx={TableBottomtext}>
                          {row?.DiscountedPrice * row?.ProductQuantity}
                        </Typography>
                      </TableCell>
                    </TableRow>
                  );
                })}
              </TableBody>
              <TableBody>
                <TableRow
                  sx={{
                    height: "42px",
                    backgroundColor: "#F7F7F7",
                  }}
                >
                  <TableCell
                    align="center"
                    colSpan={3}
                    rowSpan={3}
                    sx={{ borderRight: "1px solid #CDCDCD" }}
                  >
                    {/* <Typography sx={TableBottomtext}>
                    Total Amount Before Tax
                  </Typography> */}
                  </TableCell>

                  <TableCell
                    align="center"
                    colSpan={1}
                    rowSpan={1}
                    sx={{ borderRight: "1px solid #CDCDCD" }}
                  ></TableCell>
                  <TableCell
                    align="center"
                    colSpan={1}
                    rowSpan={1}
                    sx={{ borderRight: "1px solid #CDCDCD" }}
                  ></TableCell>
                  <TableCell
                    align="center"
                    colSpan={1}
                    rowSpan={1}
                    sx={{ borderRight: "1px solid #CDCDCD" }}
                  >
                    <Typography sx={TableBottomtext}>{totalAmount}</Typography>
                  </TableCell>
                  <TableCell
                    align="center"
                    colSpan={1}
                    rowSpan={1}
                    sx={{ borderRight: "1px solid #CDCDCD" }}
                  >
                    <Typography sx={TableBottomtext}>
                      {totatlTaxableAmount}
                    </Typography>
                  </TableCell>
                  <TableCell
                    sx={{
                      p: 0,
                      maxWidth: "200px",
                      mx: "auto",
                      borderRight: "1px solid #CDCDCD",
                    }}
                    align="center"
                  >
                    <Typography sx={TableBottomtext}>
                      {TotalDiscount}
                    </Typography>
                  </TableCell>
                  <TableCell
                    align="center"
                    colSpan={1}
                    rowSpan={1}
                    sx={{ borderRight: "1px solid #CDCDCD" }}
                  >
                    <Typography sx={TableBottomtext}>
                      {TotalAmountWithTransportationData}
                    </Typography>
                  </TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </TableContainer>

          <Box
            sx={{
              display: "flex",
              justifyContent: "space-between",
              width: "95%",
              mx: "auto",
              border: "1px solid #cdcdcd",
            }}
          >
            <Box
              sx={{
                width: "60%",
                height: "100%",
                borderRight: "1px solid #CDCDCD",
              }}
            >
              <Box
                sx={{
                  background: "#156DB6",
                  borderRadius: "3px 0px 0px 3",
                  display: "flex",
                  justifyContent: "center",
                }}
              >
                <Typography sx={TableTextStyle}>
                  Total amount in words
                </Typography>
              </Box>
              <Box
                sx={{
                  width: "100%",
                  display: "flex",
                  justifyContent: "center",
                  alignItems: "center",
                  height: "100%",
                  minHeight: "100px",
                }}
              >
                <Typography
                  sx={{
                    ...TableTotaltextStyle,
                    fontWeight: 600,
                    fontSize: "13px",
                  }}
                >
                  <NumberToWord
                    number={
                      Number(TotalAmountWithTransportationData) +
                      (totatlTaxableAmount * totalGST) / 100
                    }
                  />
                </Typography>
              </Box>
            </Box>
            <Box sx={{ width: "40%", height: "auto", display: "grid" }}>
              {InvoiceData?.IsIGST ? (
                <Table>
                  <TableRow>
                    <TableCell
                      sx={{ pl: 1, py: 0.5, borderBottom: "none" }}
                      colSpan={1}
                    >
                      <Typography sx={TableTotaltextStyle}>IGST</Typography>
                    </TableCell>
                    <TableCell
                      sx={{ px: 1, py: 0.5, borderBottom: "none" }}
                      align="center"
                    >
                      <Typography sx={TableBottomtext}>{totalGST} %</Typography>
                    </TableCell>
                    <TableCell
                      sx={{ px: 1, py: 0.5, borderBottom: "none" }}
                      align="right"
                    >
                      <Typography sx={TableBottomtext}>
                        {(totatlTaxableAmount * totalGST) / 100}
                      </Typography>
                    </TableCell>
                  </TableRow>
                </Table>
              ) : (
                <Table>
                  <TableRow>
                    <TableCell
                      sx={{ pl: 1, py: 0.5, borderBottom: "none" }}
                      colSpan={1}
                    >
                      <Typography sx={TableTotaltextStyle}>CGST</Typography>
                    </TableCell>
                    <TableCell
                      sx={{ px: 1, py: 0.5, borderBottom: "none" }}
                      align="center"
                    >
                      <Typography sx={TableBottomtext}>
                        {totalGST / 2} %
                      </Typography>
                    </TableCell>
                    <TableCell
                      sx={{ px: 1, py: 0.5, borderBottom: "none" }}
                      align="right"
                    >
                      <Typography sx={TableBottomtext}>
                        {(totatlTaxableAmount * totalGST) / 100 / 2}
                      </Typography>
                    </TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell
                      sx={{ pl: 1, py: 0.5, borderBottom: "none" }}
                      colSpan={1}
                    >
                      <Typography sx={TableTotaltextStyle}>SGST</Typography>
                    </TableCell>
                    <TableCell
                      sx={{ px: 1, py: 0.5, borderBottom: "none" }}
                      align="center"
                    >
                      <Typography sx={TableBottomtext}>
                        {totalGST / 2} %
                      </Typography>
                    </TableCell>
                    <TableCell
                      sx={{ px: 1, py: 0.5, borderBottom: "none" }}
                      align="right"
                    >
                      <Typography sx={TableBottomtext}>
                        {(totatlTaxableAmount * totalGST) / 100 / 2}
                      </Typography>
                    </TableCell>
                  </TableRow>
                </Table>
              )}
              <Box
                sx={{
                  background: "#156DB6",
                  borderRadius: "3px 0px 0px 3",
                  display: "flex",
                  justifyContent: "space-between",
                  px: 1,
                }}
              >
                <Typography sx={TableTextStyle}>Total Tax :</Typography>
                <Typography sx={TableTextStyle}>
                  {(totatlTaxableAmount * totalGST) / 100}
                </Typography>
              </Box>
              <Box
                sx={{
                  background: "#156DB6",
                  borderRadius: "3px 0px 0px 3",
                  display: "flex",
                  justifyContent: "space-between",
                  px: 1,
                }}
              >
                <Typography sx={TableTextStyle}>Invoice Total</Typography>
                <Typography sx={TableTextStyle}>
                  {Number(TotalAmountWithTransportationData) +
                    (totatlTaxableAmount * totalGST) / 100}
                </Typography>
              </Box>
            </Box>
          </Box>
          <TableContainer
            sx={{
              width: "95%",
              mx: "auto",
            }}
          >
            <Table>
              <TableHead>
                <TableRow>
                  <TableCell sx={HeaderTextStyle} colSpan={1}>
                    HSN / SAC
                  </TableCell>
                  <TableCell sx={HeaderTextStyle} colSpan={1}>
                    Taxable Value
                  </TableCell>
                  <TableCell sx={{ border: "1px solid #F3F2F3" }} colSpan={1}>
                    <Box>
                      <Typography sx={{ ...HeaderTextStyle }}>
                        CGST TAX
                      </Typography>
                      <Box
                        sx={{
                          display: "flex",
                          width: "100%",
                          justifyContent: "space-between",
                        }}
                      >
                        <Typography sx={{ ...HeaderTextStyle, width: "100%" }}>
                          Rate
                        </Typography>
                        <Typography sx={{ ...HeaderTextStyle, width: "100%" }}>
                          Amount
                        </Typography>
                      </Box>
                    </Box>
                  </TableCell>
                  <TableCell sx={{ border: "1px solid #F3F2F3" }} colSpan={1}>
                    <Box sx={{ width: "100%" }}>
                      <Typography sx={{ ...HeaderTextStyle, width: "100%" }}>
                        SGST TAX
                      </Typography>
                      <Box
                        sx={{
                          display: "flex",
                          width: "100%",
                          justifyContent: "space-between",
                        }}
                      >
                        <Typography sx={{ ...HeaderTextStyle, width: "100%" }}>
                          Rate
                        </Typography>
                        <Typography sx={{ ...HeaderTextStyle, width: "100%" }}>
                          Amount
                        </Typography>
                      </Box>
                    </Box>
                  </TableCell>
                  <TableCell sx={{ border: "1px solid #F3F2F3" }} colSpan={1}>
                    <Box>
                      <Typography sx={{ ...HeaderTextStyle }}>
                        Integrated Tax
                      </Typography>
                      <Box
                        sx={{
                          display: "flex",
                          width: "100%",
                          justifyContent: "space-between",
                        }}
                      >
                        <Typography sx={{ ...HeaderTextStyle, width: "100%" }}>
                          Rate
                        </Typography>
                        <Typography sx={{ ...HeaderTextStyle, width: "100%" }}>
                          Amount
                        </Typography>
                      </Box>
                    </Box>
                  </TableCell>
                  <TableCell sx={HeaderTextStyle} colSpan={1}>
                    Total Tax Amount
                  </TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {InvoiceData?.TaxData.map((item, index) => {
                  return (
                    <TableRow>
                      <TableCell sx={HeaderTextStyle} colSpan={1}>
                        {item.HSN}
                      </TableCell>
                      <TableCell sx={HeaderTextStyle} colSpan={1}>
                        {item?.TaxableValue}
                      </TableCell>
                      <TableCell
                        sx={{ border: "1px solid #F3F2F3" }}
                        colSpan={1}
                      >
                        <Box
                          sx={{
                            display: "flex",
                            width: "100%",
                            justifyContent: "space-between",
                          }}
                        >
                          <Typography
                            sx={{ ...HeaderTextStyle, width: "100%" }}
                          >
                            {InvoiceData?.IsIGST ? "NA" : item?.GST / 2}
                          </Typography>
                          <Typography
                            sx={{ ...HeaderTextStyle, width: "100%" }}
                          >
                            {InvoiceData?.IsIGST ? "NA" : item?.TotalTax / 2}
                          </Typography>
                        </Box>
                      </TableCell>
                      <TableCell
                        sx={{ border: "1px solid #F3F2F3" }}
                        colSpan={1}
                      >
                        <Box
                          sx={{
                            display: "flex",
                            width: "100%",
                            justifyContent: "space-between",
                          }}
                        >
                          <Typography
                            sx={{ ...HeaderTextStyle, width: "100%" }}
                          >
                            {InvoiceData?.IsIGST ? "NA" : item?.GST / 2}
                          </Typography>
                          <Typography
                            sx={{ ...HeaderTextStyle, width: "100%" }}
                          >
                            {InvoiceData?.IsIGST ? "NA" : item?.TotalTax / 2}
                          </Typography>
                        </Box>
                      </TableCell>
                      <TableCell
                        sx={{ border: "1px solid #F3F2F3" }}
                        colSpan={1}
                      >
                        <Box
                          sx={{
                            display: "flex",
                            width: "100%",
                            justifyContent: "space-between",
                          }}
                        >
                          <Typography
                            sx={{ ...HeaderTextStyle, width: "100%" }}
                          >
                            {InvoiceData?.IsIGST ? item?.GST : "NA"}
                          </Typography>
                          <Typography
                            sx={{ ...HeaderTextStyle, width: "100%" }}
                          >
                            {InvoiceData?.IsIGST ? item?.TotalTax : "NA"}
                          </Typography>
                        </Box>
                      </TableCell>
                      <TableCell sx={HeaderTextStyle} colSpan={1}>
                        {item?.TotalTax}
                      </TableCell>
                    </TableRow>
                  );
                })}
              </TableBody>
            </Table>
          </TableContainer>
          <Box>
            <Grid container sx={{ width: "95%", mx: "auto" }}>
              <Grid item xl={6} lg={6} md={6}>
                <Box
                  sx={{
                    background: "#156DB6",
                    border: "1px solid #F3F2F3",
                    padding: "1rem",
                  }}
                >
                  <Typography sx={bankDetailsTextStyle}>
                    Bank Details : Name : Sellers Bank Details
                  </Typography>
                </Box>
                <Box>
                  <Typography sx={sellercOmpanyDetailsTextStyle}>
                    Account no. : {InvoiceData?.BankDetails?.AccountNumber}
                  </Typography>
                  <Typography sx={sellercOmpanyDetailsTextStyle}>
                    IFS Code : {InvoiceData?.BankDetails?.IFSC}
                  </Typography>
                  <Typography sx={sellercOmpanyDetailsTextStyle}>
                    Branch Name : {InvoiceData?.BankDetails?.BranchName}
                  </Typography>
                  <Typography sx={sellercOmpanyDetailsTextStyle}>
                    Bank Name : {InvoiceData?.BankDetails?.BankName}
                  </Typography>
                </Box>
              </Grid>
              <Grid item xl={6} lg={6} md={6} sx={{ padding: "1rem" }}>
                <Typography
                  sx={{
                    ...bankDetailsTextStyle,
                    color: "#858585",
                    textAlign: "center",
                  }}
                >
                  For Seller Company
                </Typography>
              </Grid>
            </Grid>
            <Grid
              container
              sx={{ width: "95%", mx: "auto", border: "1px solid #F3F2F3" }}
            >
              <Grid
                item
                xl={12}
                lg={12}
                sx={{ border: "1px solid #F3F2F3", padding: "1rem" }}
              >
                <Typography
                  sx={{
                    ...lastMetaTextStyle,
                    color: "#858585",
                    marginBottom: "1rem",
                  }}
                >
                  Certified that the particulars given above are true and
                  correct ( E & OE )
                </Typography>
              </Grid>
              <Grid item xl={12} lg={12} sx={{ border: "1px solid #F3F2F3" }}>
                <Typography
                  sx={{
                    ...lastMetaTextStyle,
                    color: "#858585",
                    textAlign: "center",
                  }}
                >
                  This is a computer generated invoice
                </Typography>
              </Grid>
            </Grid>
            <Box sx={{ textAlign: "center", gap: "2rem", marginTop: "2rem" }}>
              <Button
                sx={{ ...printbuttonStyle, marginRight: "2rem" }}
                onClick={handlePrint1}
              >
                Print
              </Button>
              <Button sx={printbuttonStyle}>Download</Button>
            </Box>
          </Box>
        </Box>
      </Paper>
    </Paper>
  );
};

export default FinalInvoice;

const ButtonStyleForAcceptAndReject = {
  width: "100%",
  height: "40px",
  maxWidth: "200px",
  borderRadius: "6px",
  bgcolor: "#156DB6",
  textTransform: "none",
  color: "#fff",
  fontFamily: "Poppins",
  fontStyle: "normal",
  fontWeight: 500,
  fontSize: "16px",
  color: "#FFFFFF",
  textAlign: "center",
  alignContent: "center",
  alignItems: "center",
  justifyContent: "center",
  display: "flex",
  cursor: "pointer",
};

const BuyerInfoText = {
  fontFamily: "Poppins",
  fontStyle: "normal",
  fontWeight: 500,
  fontSize: "16px",
  lineHeight: "24px",
  textAlign: "right",
  color: "#000000",
};

const BuyerInfoTextTwo = {
  fontFamily: "Poppins",
  fontStyle: "normal",
  fontWeight: 500,
  fontSize: "16px",
  lineHeight: "24px",
  textAlign: "left",
  color: "#6B7A99",
  ml: 2,
};

const InfoBoxAmountText = {
  fontFamily: "Poppins",
  fontStyle: "normal",
  fontWeight: 400,
  fontSize: "16px",
  lineHeight: "24px",
  color: " #282828",
};

const SelectedItemsTetxStyle = {
  fontFamily: "Poppins",
  fontStyle: "normal",
  fontWeight: 500,
  fontSize: "16px",
  lineHeight: "27px",

  color: "#6B7A99",
};

const TextStyleTitle = {
  fontFamily: "Poppins",
  fontStyle: "normal",
  fontWeight: 500,
  fontSize: "14px",
  lineHeight: "20px",
  textAlign: "left",
  color: "#505050",
  opacity: 1,

  width: "120px",
  overflow: "hidden",
  textOverflow: "ellipsis",
  whiteSpace: "nowrap",
};

const FeeBoxText = {
  fontFamily: "Poppins",
  fontStyle: "normal",
  fontWeight: 400,
  fontSize: "16px",
  lineHeight: "24px",
  color: "#6B7A99",
};

const CommongTextStyle = {
  fontFamily: "Poppins",
  fontStyle: "normal",
  fontWeight: 500,
  fontSize: "12px",
  lineHeight: "21px",
  color: "#6B7A99",
};

const TextStyleTwo = {
  fontFamily: "Poppins",
  fontStyle: "normal",
  fontWeight: 500,
  fontSize: "12px",
  lineHeight: "20px",
  textAlign: "left",
  color: "#505050",
  opacity: 1,
};

const TableTextStyle = {
  fontFamily: "Poppins",
  fontStyle: "normal",
  fontWeight: 500,
  fontSize: "10px",
  lineHeight: "20px",
  color: "#FFFFFF",
};

const TableBottomtext = {
  fontFamily: "Poppins",
  fontStyle: "normal",
  fontWeight: 500,
  fontSize: "12px",
  lineHeight: "20px",
  color: "#050505",
};

const TableTotaltextStyle = {
  fontFamily: "Poppins",
  fontStyle: "normal",
  fontWeight: 500,
  fontSize: "12px",
  lineHeight: "20px",
  color: "#050505",
  opacity: 1,
};

const TextLastStyle = {
  fontFamily: "Poppins",
  fontStyle: "normal",
  fontWeight: 600,
  fontSize: "12px",
  lineHeight: "20px",
  color: "#050505",
  opacity: 1,
};

const TAndCStyle = {
  fontFamily: "Poppins",
  fontStyle: "normal",
  fontWeight: 600,
  fontSize: "12px",
  lineHeight: "17px",
  color: "rgba(5, 5, 5, 0.2)",
  opacity: 1,
};

const BanktText = {
  fontFamily: "Poppins",
  fontStyle: "normal",
  fontWeight: 500,
  fontSize: "10px",
  lineHeight: "11px",
  color: "#505050",
};

const BanktbottomText = {
  fontFamily: "Poppins",
  fontStyle: "normal",
  fontWeight: 500,
  fontSize: "9px",
  lineHeight: "11px",
  color: "#505050",
};
const HeaderTextStyle = {
  fontFamily: "Poppins",
  fontStyle: "normal",
  fontWeight: 600,
  fontSize: "12px",
  // lineHeight:"20px",
  textAlign: "center",

  color: "#505050",
  border: "1px solid #F3F2F3",
  opacity: 0.7,
};

const tablebodyTextStyle = {
  fontFamily: "Poppins",
  fontStyle: "normal",
  fontWeight: 600,
  fontSize: 12,
  lineHeight: "20px",
  textAlign: "center",

  color: "#6B7A99",

  opacity: 0.7,
};
const bankDetailsTextStyle = {
  fontFamily: "Poppins",
  fontStyle: "normal",
  fontWeight: 500,
  fontSize: "10px",
  lineHeight: "15px",
  color: "#FFFFFF",
};
const sellercOmpanyDetailsTextStyle = {
  fontFamily: "Poppins",
  fontStyle: "normal",
  fontWeight: 600,
  fontSize: "12px",
  lineHeight: "20px",
  // textAlign: "center",
  color: "#505050",
  opacity: 0.7,
};
const lastMetaTextStyle = {
  fontFamily: "Poppins",
  fontStyle: "normal",
  fontWeight: 500,
  fontSize: "8px",
  lineHeight: "20px",

  color: "#6B7A99",

  opacity: 0.7,
};
const printbuttonStyle = {
  fontFamily: "Poppins",
  fontStyle: "normal",
  fontWeight: 700,
  fontSize: "14px",
  lineHeight: "21px",
  textAlign: "center",
  textTransform: "none",
  color: "#8272B5",
  border: "1px solid #8272B5",
  padding: "0.8rem 2rem",
};
